"""Provider-neutral base classes for language model adapters.

This module defines the common contract used by the project to call LLM
providers without coupling workflow code to a specific SDK. Concrete providers
only need to implement plain text calls and one-shot structured calls; retry
orchestration, retry prompt construction, and token tracking live here.
"""

from abc import ABC, abstractmethod
from typing import TypeVar
from pydantic import BaseModel, ValidationError

from kyrg.llms.error import (
    StructuredOutputError,
    StructuredOutputParsingError,
    format_structured_error,
    build_retry_prompt,
)

OutputT = TypeVar("OutputT", bound=BaseModel)


class LLMBase(ABC):
    """Abstract interface implemented by all LLM provider adapters.

    The base class intentionally exposes a small surface:

    - ``invoke`` / ``ainvoke`` for plain text generation.
    - ``structured`` / ``astructured`` for Pydantic structured output with
      retry support.
    - ``token_usage`` for retrieving the latest provider usage metadata.

    Concrete providers implement ``_structured_once`` and
    ``_astructured_once`` instead of overriding ``structured`` directly. That
    keeps retry behavior consistent across OpenAI, Gemini, LangChain, and any
    future provider.
    """
    
    def __init__(self, max_attempts: int = 3):
        """Initialize shared retry and token tracking state.

        Args:
            max_attempts: Maximum number of attempts for structured output
                generation. A value of ``1`` disables retry prompt generation.

        Note:
            Token usage stores the latest call values, not an accumulated sum.
            Workflow nodes are responsible for accumulating usage through
            graph reducers when needed.
        """
        self.max_attempts = max_attempts
        self._input_tokens = 0
        self._output_tokens = 0
    
    @abstractmethod
    def invoke(self, prompt: str) -> str:
        """Generate plain text from a prompt.

        Args:
            prompt: Complete prompt to send to the provider.

        Returns:
            Text generated by the provider.

        Raises:
            RuntimeError: If the provider SDK call fails.
            StructuredOutputParsingError: If the underlying provider reports a
                parser failure during a plain call that uses parser-backed
                infrastructure.
        """
        ...
    
    @abstractmethod
    async def ainvoke(self, prompt: str) -> str:
        """Asynchronously generate plain text from a prompt.

        Args:
            prompt: Complete prompt to send to the provider.

        Returns:
            Text generated by the provider.

        Raises:
            RuntimeError: If the provider SDK call fails.
            StructuredOutputParsingError: If the underlying provider reports a
                parser failure during a plain call that uses parser-backed
                infrastructure.
        """
        ...

   
    def structured(
        self,
        prompt: str,
        system_prompt: str,
        prompt_cache_key: str,
        output_schema: type[OutputT],
    ) -> OutputT:
        """Generate and validate structured output.

        This method wraps provider-specific structured calls with a consistent
        retry loop. If a provider returns invalid JSON, an invalid object, or a
        Pydantic validation error, the next attempt receives a retry prompt
        containing the original prompt plus the formatted schema errors.

        Args:
            prompt: Original task prompt.
            output_schema: Pydantic model expected from the provider.

        Returns:
            An instance of ``output_schema``.

        Raises:
            StructuredOutputError: If all attempts fail. The final validation
                or parsing error is preserved as ``__cause__``.
        """
        
        current_prompt = prompt
        last_error: ValidationError | StructuredOutputParsingError | None = None
    
        for attempt in range(1, self.max_attempts + 1):
            try:
                return self._structured_once(
                    current_prompt,
                    system_prompt,
                    prompt_cache_key,
                    output_schema,
                )
            except (ValidationError, StructuredOutputParsingError) as error:
                last_error = error

                if attempt == self.max_attempts:
                    break

                current_prompt=build_retry_prompt(
                    original_prompt=prompt,
                    errors=format_structured_error(error),
                )

        raise StructuredOutputError(
            f"{output_schema.__name__} remained invalid after "
            f"{self.max_attempts} attempts"
        ) from last_error
    
    async def astructured(
        self,
        prompt: str,
        system_prompt: str,
        prompt_cache_key: str,
        output_schema: type[OutputT],
    ) -> OutputT:
        """Asynchronously generate and validate structured output.

        Async equivalent of ``structured``. It uses the same retry semantics
        and returns the same schema type.

        Args:
            prompt: Original task prompt.
            output_schema: Pydantic model expected from the provider.

        Returns:
            An instance of ``output_schema``.

        Raises:
            StructuredOutputError: If all attempts fail. The final validation
                or parsing error is preserved as ``__cause__``.
        """
        
        current_prompt = prompt
        last_error: ValidationError | StructuredOutputParsingError | None = None
    
        for attempt in range(1, self.max_attempts + 1):
            try:
                return await self._astructured_once(
                    current_prompt,
                    system_prompt,
                    prompt_cache_key,
                    output_schema,
                )
            except (ValidationError, StructuredOutputParsingError) as error:
                last_error = error

                if attempt == self.max_attempts:
                    break

                current_prompt=build_retry_prompt(
                    original_prompt=prompt,
                    errors=format_structured_error(error),
                )

        raise StructuredOutputError(
            f"{output_schema.__name__} remained invalid after "
            f"{self.max_attempts} attempts"
        ) from last_error
    
        
    @abstractmethod
    def _structured_once(
        self,
        prompt: str,
        system_prompt: str,
        prompt_cache_key: str,
        output_schema: type[OutputT],
    ) -> OutputT:
        """Execute one provider-specific structured-output attempt.

        Args:
            prompt: Prompt to send for this attempt. On retries this may be a
                generated retry prompt rather than the original prompt.
            output_schema: Pydantic model expected from the provider.

        Returns:
            An instance of ``output_schema``.

        Raises:
            ValidationError: If a provider returns a dictionary that fails
                Pydantic validation.
            StructuredOutputParsingError: If the provider cannot return a
                parseable structured object.
            RuntimeError: If the provider SDK call fails.
        """
        ...
        
    @abstractmethod
    async def _astructured_once(
        self,
        prompt: str,
        system_prompt: str,
        prompt_cache_key: str,
        output_schema: type[OutputT],
    ) -> OutputT:
        """Execute one asynchronous provider-specific structured attempt.

        Args:
            prompt: Prompt to send for this attempt. On retries this may be a
                generated retry prompt rather than the original prompt.
            output_schema: Pydantic model expected from the provider.

        Returns:
            An instance of ``output_schema``.

        Raises:
            ValidationError: If a provider returns a dictionary that fails
                Pydantic validation.
            StructuredOutputParsingError: If the provider cannot return a
                parseable structured object.
            RuntimeError: If the provider SDK call fails.
        """
        ...
    
    def _add_token(self, input_tokens: int, output_tokens: int):
        """Store latest token usage reported by a provider call.

        Args:
            input_tokens: Number of prompt/input tokens reported by the
                provider.
            output_tokens: Number of generated/output tokens reported by the
                provider.

        Note:
            This method overwrites previous values. Workflow state reducers are
            responsible for accumulating usage across multiple nodes.
        """
        self._input_tokens = input_tokens
        self._output_tokens = output_tokens
        
        
    def token_usage(self):
        """Return latest token usage in a workflow-friendly dictionary.

        Returns:
            Dictionary with ``input_tokens``, ``output_tokens``, and
            ``total_tokens``.
        """
        total_input_tokens = self._input_tokens
        total_output_tokens = self._output_tokens
        
        return {
            "input_tokens": total_input_tokens,
            "output_tokens": total_output_tokens,
            "total_tokens": total_input_tokens + total_output_tokens,
        }
