"""Typed state contract shared by copy adaptation graph nodes.

The workflow accumulates LLM outputs, deterministic metrics, retry counters,
and final assembly data in this state. Token fields use additive reducers so
multiple node updates contribute to the total usage counters.
"""

from typing import Annotated, Any, NotRequired, TypedDict
from operator import add

from kyrg.workflows.copyanalysis.schemas import CopyAnalysisOutput, SectionType
from kyrg.workflows.copyadaptation.schemas import UserProfileOutput

class CopyAdaptationState(TypedDict):
    """Mutable graph state for adapting a reference copy to a new offer."""
    
    # Strategic analysis of the reference copy produced by CopyAnalysisWorkflow.
    copy_analysis: CopyAnalysisOutput
    # New offer profile: product, audience, pains, proof, CTA, and restrictions.
    user_profile: UserProfileOutput

    max_words_per_minute: NotRequired[int]
    min_words_per_minute: NotRequired[int]
    
    # Input tokens consumed by this workflow's LLM calls.
    input_tokens: NotRequired[Annotated[int, add]]
    # Output tokens generated by this workflow's LLM calls.
    output_tokens: NotRequired[Annotated[int, add]]
    # Total input and output tokens.
    total_tokens: NotRequired[Annotated[int, add]]

    # Reference-copy sections mapped to the user's new offer.
    mapped_sections: NotRequired[list[dict[str, Any]]]
    # Sections missing from the reference that must be created from scratch.
    sections_to_create: NotRequired[list[SectionType]]
    # Weaknesses or gaps the adapted copy should correct.
    gaps_to_fix: NotRequired[list[str]]
    # Final language for the adapted script.
    target_language: NotRequired[str]
    # Platform or channel where the VSL/creative will be used.
    platform: NotRequired[str]
    # Desired script duration in minutes.
    desired_duration: NotRequired[float]

    # Main angle selected to sell the new offer.
    main_angle: NotRequired[str]
    # Audience awareness level for the problem and solution.
    awareness_level: NotRequired[str]
    # Central promise of the new copy.
    main_promise: NotRequired[str]
    # Selected persuasion pattern, such as PAS, AIDA, BAB, or hybrid.
    persuasion_pattern: NotRequired[str]
    # Main objections the script needs to address.
    objections_to_address: NotRequired[list[str]]
    # Proof plan indicating which evidence to use in each script area.
    proof_plan: NotRequired[dict[str, Any]]
    # Unique mechanism explaining why the offer works or is different.
    unique_mechanism: NotRequired[str]

    # Written sections of the adapted script.
    sections: NotRequired[list[dict[str, Any]]]
    # Continuity, coherence, or transition issues found between sections.
    flow_issues: NotRequired[list[str]]
    # Structured review instructions for the next writing attempt.
    revision_instructions: NotRequired[list[dict[str, Any]]]
    # Number of section rewrites after failed flow review.
    retry_count_correction_section: NotRequired[int]
    
    # Number of full-script rewrites after failed validation.
    retry_count_correction_script: NotRequired[int]
    
    # Sections revised after the flow review.
    sections_revised: NotRequired[list[dict[str, Any]]]
    # Whether the flow between sections was approved.
    flow_approved: NotRequired[bool]

    # Whether the script passed final validation.
    validation_passed: NotRequired[bool]
    # Critical errors that block script usage.
    validation_errors: NotRequired[list[dict[str, Any]]]
    # Non-blocking warnings that should be shown to the user.
    validation_warnings: NotRequired[list[dict[str, Any]]]

    # Total script word count.
    word_count: NotRequired[int]
    # Explanation of what was preserved from the reference and adapted.
    adaptation_notes: NotRequired[str]
    # Sections that need real proof before production use.
    missing_proofs: NotRequired[list[str]]
    # Final consolidated workflow output.
    adapted_script: NotRequired[dict[str, Any]]

    # Snapshot of sections before the validation-correction pass.
    sections_before_script_correction: NotRequired[list[dict[str, Any]]]
    
    # Snapshot of sections after the validation-correction pass.
    sections_after_script_correction: NotRequired[list[dict[str, Any]]]
    
    # Deterministic word count, pause, duration, and duration-fit metrics.
    timing_metrics: NotRequired[dict[str, Any]]
