"""Video stabilization operations backed by FFmpeg vidstab filters.

This module contains command builders for FFmpeg's two-step stabilization
workflow. Stabilization first analyzes motion and writes transform data, then
applies those transforms to produce a stabilized output video.
"""

from kyrg.editor.base import BaseEditor
from kyrg.editor.context import MediaContext
from kyrg.editor.runner import CommandRunner


class DetectVideoStabilization(BaseEditor[MediaContext]):
    """Build an FFmpeg command that detects camera motion for stabilization.

    The operation uses ``vidstabdetect`` and writes transform metadata to a
    sidecar file. It does not produce a transformed video directly.
    """

    def __init__(
        self,
        context: MediaContext,
        runner: CommandRunner,
        transforms_path: str = "transforms.trf",
        shakiness: int = 5,
        accuracy: int = 15,
    ) -> None:
        """Initialize stabilization detection options.

        Args:
            context: Input path and null output target used by FFmpeg.
            runner: Command runner responsible for executing the command.
            transforms_path: Path where transform data should be written.
            shakiness: Expected camera shakiness level.
            accuracy: Motion detection accuracy level.
        """

        super().__init__(context, runner)
        self.transforms_path = transforms_path
        self.shakiness = shakiness
        self.accuracy = accuracy

    def build_command(self) -> list[str]:
        """Return the FFmpeg command for stabilization motion detection."""

        return [
            "ffmpeg",
            "-y",
            "-i",
            self.context.input_path,
            "-vf",
            (
                f"vidstabdetect=shakiness={self.shakiness}:"
                f"accuracy={self.accuracy}:"
                f"result={self.transforms_path}"
            ),
            "-f",
            "null",
            self.context.output_path,
        ]


class StabilizeVideo(BaseEditor[MediaContext]):
    """Build an FFmpeg command that applies stabilization transforms."""

    def __init__(
        self,
        context: MediaContext,
        runner: CommandRunner,
        transforms_path: str = "transforms.trf",
        smoothing: int = 30,
    ) -> None:
        """Initialize stabilization transform options.

        Args:
            context: Input and output paths used by the FFmpeg command.
            runner: Command runner responsible for executing the command.
            transforms_path: Path to transform data generated by detection.
            smoothing: Smoothing window used by ``vidstabtransform``.
        """

        super().__init__(context, runner)
        self.transforms_path = transforms_path
        self.smoothing = smoothing

    def build_command(self) -> list[str]:
        """Return the FFmpeg command for applying stabilization."""

        return [
            "ffmpeg",
            "-y",
            "-i",
            self.context.input_path,
            "-vf",
            (
                f"vidstabtransform=input={self.transforms_path}:"
                f"smoothing={self.smoothing}"
            ),
            self.context.output_path,
        ]
