"""Input and output schemas for voice generation.

These Pydantic models define the public data contract used by voice adapters.
Inputs describe what should be sent to a provider, while outputs normalize
provider responses into stable objects that callers can depend on.
"""

from typing import Any

from pydantic import BaseModel, Field


class TextToSpeechInput(BaseModel):
    """Input payload for text-to-speech generation."""

    model: str = Field(description="Provider-specific text-to-speech model.")
    text: str = Field(description="Text that should be converted into speech.")
    output_path: str = Field(description="Path where the generated audio is saved.")
    voice: str = Field(description="Provider-specific voice id or voice name.")
    settings: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific optional settings.",
    )


class VoiceCloneInput(BaseModel):
    """Input payload for creating a cloned voice from audio samples."""

    name: str = Field(description="Name assigned to the cloned voice.")
    audio_paths: list[str] = Field(description="Audio sample paths used for cloning.")
    description: str | None = Field(
        default=None,
        description="Optional description for the cloned voice.",
    )
    labels: dict[str, str] = Field(
        default_factory=dict,
        description="Provider labels attached to the cloned voice.",
    )
    settings: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific optional cloning settings.",
    )


class SpeechToSpeechInput(BaseModel):
    """Input payload for converting an audio file into another voice."""

    model: str = Field(description="Provider-specific speech-to-speech model.")
    audio_path: str = Field(description="Source audio path to convert.")
    output_path: str = Field(description="Path where the converted audio is saved.")
    voice: str = Field(description="Provider-specific target voice id or voice name.")
    settings: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific optional speech-to-speech settings.",
    )


class VoiceDesignInput(BaseModel):
    """Input payload for generating temporary voice design previews."""

    output_dir: str = Field(description="Directory where preview audio files are saved.")
    name: str | None = Field(
        default=None,
        description="Optional intended name for the designed voice.",
    )
    text: str | None = Field(
        default=None,
        description="Optional text used by the provider to generate previews.",
    )
    description: str = Field(description="Natural-language voice description.")
    settings: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-specific optional voice design settings.",
    )


class VoiceDesignPreview(BaseModel):
    """A temporary voice preview generated by a voice design provider."""

    generated_voice_id: str = Field(
        description="Temporary provider id for this generated voice preview."
    )
    audio_path: str = Field(description="Local path where the preview audio was saved.")
    media_type: str | None = Field(
        default=None,
        description="Preview audio media type returned by the provider.",
    )
    duration_secs: float | None = Field(
        default=None,
        description="Preview audio duration in seconds, when provided.",
    )
    language: str | None = Field(
        default=None,
        description="Detected or generated preview language, when provided.",
    )


class VoiceDesignOutput(BaseModel):
    """Normalized output for voice design preview generation."""

    provider: str = Field(description="Provider that generated the design previews.")
    text: str | None = Field(
        default=None,
        description="Text used or generated by the provider for the previews.",
    )
    previews: list[VoiceDesignPreview] = Field(
        default_factory=list,
        description="Generated preview voices available for user selection.",
    )
    raw_response: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider response metadata preserved for debugging.",
    )


class VoiceDesignSaveInput(BaseModel):
    """Input payload for saving a selected voice design preview."""

    generated_voice_id: str = Field(
        description="Temporary preview id selected to become a permanent voice."
    )
    name: str = Field(description="Final name assigned to the saved voice.")
    description: str = Field(description="Final description assigned to the saved voice.")
    labels: dict[str, str | None] = Field(
        default_factory=dict,
        description="Provider labels attached to the saved voice.",
    )
    

class VoiceOutput(BaseModel):
    """Normalized output for actions that produce an audio file."""

    audio_path: str = Field(description="Local path of the generated audio file.")
    provider: str = Field(description="Provider that generated the audio.")
    model: str = Field(description="Model used to generate the audio.")
    voice_id: str | None = Field(
        default=None,
        description="Provider voice id or voice name used for generation.",
    )
    output_format: str | None = Field(
        default=None,
        description="Provider audio format, when available.",
    )
    raw_response: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider response metadata preserved for debugging.",
    )


class VoiceIdentityOutput(BaseModel):
    """Normalized output for actions that create or save a reusable voice."""

    provider: str = Field(description="Provider that created or saved the voice.")
    voice_id: str = Field(description="Permanent provider voice id.")
    name: str | None = Field(
        default=None,
        description="Voice name returned by the adapter.",
    )
    description: str | None = Field(
        default=None,
        description="Voice description returned by the adapter.",
    )
    raw_response: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider response metadata preserved for debugging.",
    )
